### ISSUE TITLE
Add HydroShare Links to Site Details Page

### ISSUE THREAD

**Issue by daniel-slaugh** [hydroserver2/hydroserver#140]
The site details page at https://lrodata.usu.edu/site/LR_Mendon_AA has three buttons above the datastreams which link to HydroShare resources. This functionality may be missed by LRO users switching over to HydroServer. Add buttons for:

- [ ] Raw Data
- [ ] Quality Controlled Data
- [ ] Rating Curve

**Comment by horsburgh** [comment]
Given that we want HydroServer to be a generic implementation for anyone, is there a way to do this generically so that it isn't LRO specific? I didn't add a specific issue for this because links/buttons to the raw and quality controlled data in HydroShare should be part of the HydroShare archival integration. We might have to discuss how to implement the link to the rating curve though because that is just an external resource (happens to be in HydroShare) that is related to the monitoring site.
