### ISSUE TITLE
Unable to make child fields undefined with api patch method

### ISSUE THREAD

**Issue by Maurier** [hydroserver2/hydroserver#16]
The `createPatchObject` method won't produce an accurate payload when trying to make a child property `undefined`.

Steps to reproduce:
- Update your user profile and add `Organization`  data.
- Go to edit your profile and uncheck the Organization affiliation checkbox.
- Save changes.
- Look at the outgoing request. The resulting payload will be an empty object, instead of an object with the `Organization` field as `undefined`.

**Comment by daniel-slaugh** [comment]
@Maurier The createPatchObject is working correctly. In fact, createPatchObject.spec.ts has a test 'should handle null values in nested objects' specifically for this case. 

undefined = don't change this value in the backend 
null = send a null to the backend to update this value to null in the database
an object or array = update related fields with the contained data

The problem comes from commit 5763840986912c981288c022fc064cea7988c59a where the account form was changed from sending a null value to an undefined value for organizations when the user unchecks the organization affiliation checkbox and submits. Please revert your commit and refrain from refactoring working code. Also if you are going to refactor code, don't combine it in another commit with a different name.  This will make it easier to track newly introduced bugs.

**Comment by daniel-slaugh** [comment]
As agreed upon in the meeting with Ken, Maurier, and myself I reverted the AccountForm business logic. I keep Maurier's formatting changes for the component. Vuelidate might be useful to add in the future, but for now I commented out the Vuelidate rules.ts code while we can get the core functionality stable.
