### ISSUE TITLE
Result Qualifiers unprotected from deletion

### ISSUE THREAD

**Issue by daniel-slaugh** [hydroserver2/hydroserver#17]
Problem:
When on the edit metadata page, going to delete a result qualifier always opens the modal saying it isn't being used by any datastreams and is safe to delete, even when it's not. 

Expected Functionality:
Trying to delete either RESULTQUALIFIER1 or RESULTQUALIFIER2 should prevent deletion with a modal that prompts them to delete related datastreams first or reassign the result qualifier

Reproducing the problem: 
loaddata for Paul's Miami test case
Try to delete RESULTQUALIFIER1 or 2

**Comment by kjlippold** [comment]
This protection needs to be implemented in our Django models to maintain data integrity at the API level.

Normally with a many-to-many relationship between observations and result qualifiers, this would be handled automatically by Django. Since we're using an array field in observations instead of a junction table, we get the correct behavior if an observation is deleted, but not if a result qualifier is deleted.

To avoid scanning the entire observations table anytime we need to delete a result qualifier, we should set up a rule in the model to check only observations owned by the owner of the result qualifier being deleted. If that result qualifier is being used in any of those observations, the delete request should be blocked until any observations referencing the result qualifier are deleted or updated with different result qualifiers.

**Comment by kjlippold** [comment]
https://github.com/hydroserver2/hydroserver-webapp-back/pull/164
