### ISSUE TITLE
Sign up with Google is not working

### ISSUE THREAD

**Issue by amabdallah** [hydroserver2/hydroserver#176]
### Steps to Reproduce

![image](https://github.com/hydroserver2/hydroserver/assets/3268971/ad85d6a2-35ed-4dfb-9608-807ea3e8fd7c)

### Expected Behavior

Sign up with Google to work

### Actual Behavior

![image](https://github.com/hydroserver2/hydroserver/assets/3268971/c3499fed-d38e-4676-8df5-4594569cf3f0)

**Comment by kjlippold** [comment]
Hi @amabdallah, can you try logging in again, the issue should be resolved now. We're also working on switching over from https://beta.hydroserver2.org to https://playground.hydroserver.org. They're both connected to the same database so feel free to use either one for now, but if you're doing some testing it might be easier to use the playground instance rather than beta.

**Comment by amabdallah** [comment]
Thanks! I think now it works. It's just our system doesn't allow me to use my Gmail to sign up.
![image](https://github.com/hydroserver2/hydroserver/assets/3268971/df0f44d3-16a8-4135-8ace-130cffad29b6)
