### ISSUE TITLE
Anonymous users are sometimes redirected to login from public pages

### ISSUE THREAD

**Issue by kjlippold** [hydroserver2/hydroserver#39]
### Steps to Reproduce

- Visit a site details page without logging in and wait for a few minutes.
- Click around, try to navigate to some other site details page.
- Sometimes the user will be directed to sign in (usually after about 5 minutes or so), even if they stay on public pages.

### Expected Behavior

As long as anonymous users don't go to a page requiring a login, they shouldn't be prompted to log in.

### Actual Behavior

Sometimes anonymous users are redirected to the login page when they shouldn't be.

### Any additional comments?

This is probably related to refresh token logic on the frontend where it thinks a user who hasn't logged in has an expired session and prompts them to log in again.

**Comment by daniel-slaugh** [comment]
Does anything display in the console when this happens? I tried to reproduce the error for about 30 minutes on localhost and Beta without success.

This may have been fixed this commit: 74371c3 - Guests were redirected because the GET metadata endpoint wasn't public.  

If not, I think you're right that this is related to the refresh token logic given the user is directed after about 5 minutes and the refresh token is checked every 10.
